#########
# PROJECT
#########

# Replace the values here with your project` information.
project:
  # The name of the organisation or entity that owns this project
  organisation: "Unassociated thought"
  # A live web address for the organisation
  url: ""
  # The default contact email address
  email: "christi.1415@gmail.com"
  # The name of the project of books in this folder.
  name: "Philosophical, Political, and Economic thought"
  # A one-liner about this project. Useful for Open Graph metadata.
  description: "Books created by Christina Tromp, using Arthur Attwell's Electric Book workflow"
  # The logo of the organisation, saved web-ready in /assets
  logo: "ac-logo.jpg"
  # An image in /assets that stands for the project
  image: "cover.jpg"
  # Credit line, by default in the footer, overidden in locales.yml
  credit: "Built with the [Electric Book](http://electricbook.works)"
  # Primary language code for this project as a whole
  language: "en"
  # App bundle ID unique across all app stores
  app-id: com.example.myapp
  # Version. You must change this with each app update
  version: "1.0.0"


########
# TITLES
########

## Metadata follows [Dublin Core](https://en.wikipedia.org/wiki/Dublin_Core#DCMI_Metadata_Terms)
## Custom fields added to standard DC terms: subtitle, publisher URL
## When listing files, exlude file extensions, and surround them in quotes
## especially if they contain only numbers.

works:
  - directory: "book"
    title: "The Value of Cooperation and the Reasons for Action"
    subtitle: "When Is Cooperation Rational?"
    creator: "Christina Tromp" # E.g. the author
    contributor: "" # E.g. other contributors
    subject: "PHI019000" # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (http://editeur.dyndns.org/bic_categories)
    description: "In this paper I look at Social Dilemmas as described by Rational Choice Theory, and more broadly, neo-classical economics. Although Social Dilemmas have no 'technical solution', when we discount the fundamental assumptions of neo-classical economics, a sketch of rational actors who are capable of cooperating to avert Social Dilemmas becomes possible. I argue that the assumptions of Rational Choice theory and neo-classical economics fail to explain the social problems that rational actors face, and overlook important elements of rationality which can describe actors in social dilemmas and guide our solutions." # E.g. the blurb
    publisher: "" # E.g. the publisher, imprint or brand name
    publisher-url: ""
    date: "2018-06-15" # YYYY-MM-DD e.g. publication date
    modified: "" # YYYY-MM-DD e.g. date of last revision
    type: "Thesis" # e.g. Novel, Poetry, Memoir
    identifier: "" # e.g. ISBN or UUID
    source: "" # e.g. parent ISBN or ISTC
    language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
    relation: "" # e.g. other edition ISBN
    coverage: "" # e.g. geographic place or chronological time span
    rights: "You are free to share or adapt this material under a CC BY 3.0 ZA license with the following terms: You must give appropriate credit, provide a link to the original work, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use. In addition, you may not apply legal terms or technological measures that legally restrict others from accessing the reproduced work." # e.g. a copyright statement
    image: "cover.jpg"
    products: # Metadata for each product for this title (only use values that override parent metadata)
      print-pdf: 
        date: "2016-05-07" # YYYY-MM-DD e.g. publication or creation date
        format: "Print" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "01-01"
          - "01"
          - "02"
          - "03"
          - "04"
          - "05"
          - "06"
          - "07"
          - "08"
          - "50-01-bibliography"
        toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Introduction"
            file: "01-01"
          - label: "**1** Rational Choice as Utility Maximization"
            file: "01"
          - label: "**2** A Paradox of Rational Choice as Utility Maximization"
            file: "02"
          - label: "**3** Problems as the Absence of Markets"
            file: "03"
          - label: "**4** Reasons, Motivation and Value"
            file: "04"
          - label: "**5** Rational Action as Based on Good Reasons "
            file: "05"
          - label: "**6** The Context for Appropriate Cooperation"
            file: "06"
          - label: "**7** The Outcomes of a Reasonable Theory of Rationality"
            file: "07"
          - label: "Conclusion"
            file: "08"
          - label: "Bibliography"
            file: "50-01-bibliography"
      web:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital online" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "index"
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "01-01"
          - "01"
          - "02"
          - "03"
          - "04"
          - "05"
          - "06"
          - "07"
          - "08"
          - "50-01-bibliography"
        nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Introduction"
            file: "01-01"
          - label: "**1** Rational Choice as Utility Maximization"
            file: "01"
          - label: "**2** A Paradox of Rational Choice as Utility Maximization"
            file: "02"
          - label: "**3** Problems as the Absence of Markets"
            file: "03"
          - label: "**4** Reasons, Motivation and Value"
            file: "04"
          - label: "**5** Rational Action as Based on Good Reasons "
            file: "05"
          - label: "**6** The Context for Appropriate Cooperation"
            file: "06"
          - label: "**7** The Outcomes of a Reasonable Theory of Rationality"
            file: "07"
          - label: "Conclusion"
            file: "08"
          - label: "Bibliography"
            file: "50-01-bibliography"
        start-page: "0-3-contents" # At which file should users start reading?
        contents-page: "0-3-contents" # Your contents-page file, if you have one.
      epub:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "9780000000000" # e.g. ISBN or UUID
        image: "cover.jpg"
        start-page: "0-3-contents"
        contents-page: "0-3-contents"
        files: # add a value to any file to set any of the guide types listed in http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.6
          - "0-0-cover": "cover"
          - "0-1-titlepage": "title-page"
          - "0-2-copyright": "copyright-page"
          - "0-3-contents": "toc"
          - "01": "text"
          - "02"
        toc: # For each menu item, include at least label and file (epub requires file). Optionally add id (for deep linking) and children.
          - label: "Frontmatter"
            file: "0-0-cover"
            children:
              - label: "Cover"
                file: "0-0-cover"
              - label: "Title page"
                file: "0-1-titlepage"
              - label: "Copyright"
                file: "0-2-copyright"
          - label: "Contents"
            file: "0-3-contents"
          - label: "Chapter One"
            file: "01"
            id: "1-hello-world"
          - label: "Chapter Two"
            file: "02"
            id: "2-goodbye-world"
            children:
              - label: "Subsection"
                file: "02"
                id: "example-id"
      screen-pdf:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "0-0-cover"
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "01"
          - "02"
      app:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        image: "cover.jpg"
        files:
          - "index"
          - "0-1-titlepage"
          - "0-2-copyright"
          - "0-3-contents"
          - "01": "Chapter One"
          - "02": "Chapter Two"
        nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
          - label: "Frontmatter"
            children:
              - label: "Cover"
                file: "index"
              - label: "Title page"
                file: "0-1-titlepage"
              - label: "Copyright"
                file: "0-2-copyright"
          - label: "Contents"
            file: "0-3-contents"
          - label: "Chapter One"
            file: "01"
            id: "1-hello-world"
          - label: "Chapter Two"
            file: "02"
            id: "2-goodbye-world"
            children: 
              - label: "Subsection"
                file: "02"
                id: "example-id"
        start-page: "0-3-contents" # At which file should users start reading?
        contents-page: "0-3-contents" # Your contents-page file, if you have one.
    # variants:
    #   - variant: myvariant
    #     identifier: ""
    #     products:
    #       print-pdf:
    #         identifier: ""
